[package]
name = "incept"
version = "0.1.0"
edition = "2021"

[dependencies]
evdev = "0.12.2"
uinput = "0.1.3"
quick-xml = "0.28"
dirs = "5.0"
aya = { version = "0.13.1", features = ["async_tokio"] }
aya-log = "0.2.1"
tokio = { version = "1", features = ["full"] }
